----------------시스템계정--------------------
--DROP USER aiWeather CASCADE;--계정 삭제
--
--create user hugme identified by hugme;
--grant resource, connect to hugme;

----------------------------------------------

--회원 식별번호 시퀀스
CREATE SEQUENCE seq_me
START WITH 1
INCREMENT BY 1
NOCACHE;

--VC 식별번호 시퀀스
CREATE SEQUENCE seq_vc
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 회원 테이블
CREATE TABLE MEMBER (
    USER_NO       NUMBER,
    USER_ID       VARCHAR2(50),
    USER_PWD      VARCHAR2(100),
    USER_NAME     VARCHAR2(100),
    NAME_SEED     RAW(16),
    ENROLLDATE    TIMESTAMP,
    MODIFYDATE    TIMESTAMP,
    STATUS        CHAR(1),

    CONSTRAINT PK_USER_NO    PRIMARY KEY (USER_NO),
    CONSTRAINT NN_USER_ID    CHECK (USER_ID IS NOT NULL),
    CONSTRAINT UQ_USER_ID    UNIQUE (USER_ID),
    CONSTRAINT NN_USER_PWD   CHECK (USER_PWD IS NOT NULL),
    CONSTRAINT UQ_MEMBER_NAME UNIQUE (USER_NAME, NAME_SEED),
    CONSTRAINT CK_STATUS     CHECK (STATUS IN ('Y', 'N'))
);
COMMENT ON TABLE MEMBER IS '회원정보';
COMMENT ON COLUMN MEMBER.USER_NO IS '식별번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '닉네임';
COMMENT ON COLUMN MEMBER.NAME_SEED IS '닉네임 시드';
COMMENT ON COLUMN MEMBER.ENROLLDATE IS '가입일';
COMMENT ON COLUMN MEMBER.MODIFYDATE IS '수정일';
COMMENT ON COLUMN MEMBER.STATUS IS '상태(Y:정상, N:탈퇴)';

-- 영상통화(화상회의) 테이블
CREATE TABLE VIDEO_CALL (
    VC_NO                NUMBER,
    USER_NO              NUMBER,
    VC_ID                VARCHAR2(50),
    VC_SESSION           VARCHAR2(50),
    VC_NAME              VARCHAR2(100),
    CREATE_TIMESTAMP     TIMESTAMP,
    MAX_PARTICIPANTS     NUMBER,
    STATUS               CHAR(1),

    CONSTRAINT PK_VC_NO      PRIMARY KEY (VC_NO),
    CONSTRAINT FK_VIDEO_CALL_USER
        FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    CONSTRAINT NN_VC_ID      CHECK (VC_ID IS NOT NULL),
    CONSTRAINT NN_VC_SESSION CHECK (VC_SESSION IS NOT NULL),
    CONSTRAINT NN_VC_NAME    CHECK (VC_NAME IS NOT NULL),
    CONSTRAINT NN_MAX_PATCIPANTS CHECK (MAX_PATCIPANTS IS NOT NULL),
    CONSTRAINT CK_STATUS     CHECK (STATUS IN ('Y', 'N'))
    
);
COMMENT ON TABLE VIDEO_CALL IS '영상통화';
COMMENT ON COLUMN VIDEO_CALL.VC_NO IS '식별번호';
COMMENT ON COLUMN VIDEO_CALL.USER_NO IS '방장 회원식별번호';
COMMENT ON COLUMN VIDEO_CALL.VC_ID IS '회의실 UUID';
COMMENT ON COLUMN VIDEO_CALL.VC_SESSION IS 'OpenVidu 세션';
COMMENT ON COLUMN VIDEO_CALL.VC_NAME IS '이름';
COMMENT ON COLUMN VIDEO_CALL.CREATE_TIMESTAMP IS '생성일';
COMMENT ON COLUMN VIDEO_CALL.MAX_PATCIPANTS IS '최대 참여인원';
COMMENT ON COLUMN VIDEO_CALL.VC_STATUS IS '상태(Y:정상, N:비활성화)';

-- 영상 통화 참여회원 테이블
CREATE TABLE VC_MEMBER (
    VC_NO        NUMBER,
    USER_NO      NUMBER,
    STATUS       CHAR(1)        DEFAULT 'Y',
    ROLE_TYPE    CHAR(1),

    CONSTRAINT FK_VC_MEMBER_VC
        FOREIGN KEY (VC_NO) REFERENCES VIDEO_CALL(VC_NO),
    CONSTRAINT FK_VC_MEMBER_USER
        FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    CONSTRAINT CK_STATUS     CHECK (STATUS IN ('Y', 'N')),
    CONSTRAINT CK_ROLE_TYPE  CHECK (ROLE_TYPE IN ('P', 'S', 'M')),
);
COMMENT ON TABLE VC_MEMBER IS '영상통화 참여회원';
COMMENT ON COLUMN VC_MEMBER.VC_NO IS '방 식별번호';
COMMENT ON COLUMN VC_MEMBER.USER_NO IS '회원 식별번호';
COMMENT ON COLUMN VC_MEMBER.STATUS IS '상태(Y:접속, N:미접속)';
COMMENT ON COLUMN VC_MEMBER.ROLE_TYPE IS '관리 권한(M:관리자, P:발표자, S:관전자)';